### ISSUE TITLE
Add a mandatory confirmation to the deletion of a filter in the Data Browser

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [code-kern-ai/refinery-ui-angular#62]
This could be a modal just like we have for embedding deletion etc..

**Comment by JWittmeyer** [comment]
personally not a fan of this since I don't like the extra x clicks. Maybe on hitting clear the filter is stored locally and can be "reset" by clicking on the clear button again?

**Comment by DerEchteFeuerpfeil** [comment]
@JWittmeyer 
Are we talking about the same thing? I mean this deletion here:
![image](https://user-images.githubusercontent.com/57487741/203324870-b81d340e-6c75-4c0a-b27b-2f4b9a1863e0.png)

It could happen that I click on this by accident and then the filter is gone without a warning. If it was by accident I don't even know which filter is missing then since there is no notification or anything.

**Comment by JWittmeyer** [comment]
oh :D sorry i thought you  meant the clear filter button
![image](https://user-images.githubusercontent.com/91723236/203326203-db8fd3d6-61dc-4024-881c-28b1e7964f17.png)

for that no problem :)

**Comment by lumburovskalina** [comment]
This issue is implemented as part of [refactoring modals with shared component](https://github.com/code-kern-ai/refinery-ui/pull/89). The estimation and steps to implement are included in that issue.
