### ISSUE TITLE
Modernize Comment Feature

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/refinery-ui-angular#72]
- gives more context of what you want to comment on. A modal mostly blocks the screen, whereas a slideover gives you full access of the actual page
- since the user isn't yet with an image the differentiation will be harder so a marker for "own comment" & a hover on the image with the email 

Example:
<img width="853" alt="image (1)" src="https://user-images.githubusercontent.com/91723236/195526197-589100d2-4840-4ebf-8411-bf75ffdba3f3.png">

**Comment by lumburovskalina** [comment]
Steps to implement the feature:
- Check Tailwind UI existing components
- Build the template with Tailwind UI according to the design mockup
- Add the implemented functionalities from the previous version
- Test and code review
